<img style="float: left; margin: 30px 15px 15px 15px;" src="https://pngimage.net/wp-content/uploads/2018/06/logo-iteso-png-5.png" width="300" height="500" /> 
    
    
### <font color='navy'> Simulación de procesos financieros. 

**Nombres:** 
    Pablo Muñoz,
    Valeria Ladrón de Guevara,
    Andrés Ramírez Villanueva.

**Fecha:** 09 de junio del 2021.

**Expedientes** : 
    if719963,
    if714513,
    if726061.
    
**Profesor:** Oscar David Jaramillo Zuluaga.
    
**Link Github**: https://github.com/munoz97/Tarea3Pablo_Valeria_Andr-s

# Tarea 3: Clase 6


> ## Tarea 3: (Usando notebook de jupyter)** 

> Usando compresión de listas o funciones map(sino recuerda como funciona observar el siguiente enlace https://www.pythonforbeginners.com/lists/list-comprehensions-in-python/), resolver los siguientes ejercicios:

>1. Resolver la siguiente ecuación recursiva usando funciones como se vió en clase
$$ D_{n}=(n-1) D_{n-1}+(n-1) D_{n-2} \quad n\ge 3$$
con $D_1=0$ y $D_2 = 1$
>3. Count the number of spaces in the following string `variable =  relaciónn  requiere,  para obtener  el  valor  de un  cierto  término,  el conocimiento de los dos anteriores`.
>4. Remove all of the vowels in a string [make a list of the non-vowels].
>5. Find all of the words in a string that are less than 4 letters.
>6. Use a dictionary comprehension to count the length of each word in a sentence.
>7. Use a nested list comprehension to find all of the numbers from 1-1000 that are divisible by any single digit besides 1 (2-9). 

### Ejercicio 1: (enunciado) Transcribirlo

Código de solución estudiante 1

In [1]:
# Código de solución estudiante 1 Pablo Muñoz
# Ejercicio 1
import numpy as np


def cong_method(D1:"Semilla inicial",D2:"Semilla inicial",n:"Número de elementos"):
    '''
    Esta función contiene la programación del método congruencial para la sucesión de la ecuación recursiva D_n = (n-1)D_(n-1) + (n-1)D_(n-1)
    '''
    D=np.zeros(n)
    D[0]=D1
    D[1]=D2
    def llenar_verctor(i):
        nonlocal D
        D[i]=((i+1)-1) * D[i-1] + ((i+1)-1 )* D[i-2]
    [llenar_verctor(i) for i in range(2,n)]  
    return D
result=cong_method(0,1,6)
result  

array([  0.,   1.,   2.,   9.,  44., 265.])

In [4]:
# Ejercicio 2
vari =  "relaciónn  requiere,  para obtener  el  valor  de un  cierto  término,  el conocimiento de los dos anteriores"
solu = [x for x in vari if x ==' ']
len(solu)

23

In [5]:
# Ejercicio 3
vocales =['a','e','i','o','u']
solucion=[x for x in vari if x not in vocales]
solucion
#sitio de ayuda "https://www.geeksforgeeks.org/python-membership-identity-operators-not-not/"

['r',
 'l',
 'c',
 'ó',
 'n',
 'n',
 ' ',
 ' ',
 'r',
 'q',
 'r',
 ',',
 ' ',
 ' ',
 'p',
 'r',
 ' ',
 'b',
 't',
 'n',
 'r',
 ' ',
 ' ',
 'l',
 ' ',
 ' ',
 'v',
 'l',
 'r',
 ' ',
 ' ',
 'd',
 ' ',
 'n',
 ' ',
 ' ',
 'c',
 'r',
 't',
 ' ',
 ' ',
 't',
 'é',
 'r',
 'm',
 'n',
 ',',
 ' ',
 ' ',
 'l',
 ' ',
 'c',
 'n',
 'c',
 'm',
 'n',
 't',
 ' ',
 'd',
 ' ',
 'l',
 's',
 ' ',
 'd',
 's',
 ' ',
 'n',
 't',
 'r',
 'r',
 's']

In [6]:
#Ejercicio 4
l = vari.split()
sol = list(filter(lambda x: len(x)<=3,l)) 
sol

['el', 'de', 'un', 'el', 'de', 'los', 'dos']

In [7]:
# Ejercicio 5
sol1 = [len(x) for x in l]
diccionario = (dict(zip(l, sol1)))
diccionario

{'relaciónn': 9,
 'requiere,': 9,
 'para': 4,
 'obtener': 7,
 'el': 2,
 'valor': 5,
 'de': 2,
 'un': 2,
 'cierto': 6,
 'término,': 8,
 'conocimiento': 12,
 'los': 3,
 'dos': 3,
 'anteriores': 10}

In [8]:
# Ejercicio 6
results = [[x for x in range(1,1001) if x % divisor == 0] for divisor in range(2,10)]
results

[[2,
  4,
  6,
  8,
  10,
  12,
  14,
  16,
  18,
  20,
  22,
  24,
  26,
  28,
  30,
  32,
  34,
  36,
  38,
  40,
  42,
  44,
  46,
  48,
  50,
  52,
  54,
  56,
  58,
  60,
  62,
  64,
  66,
  68,
  70,
  72,
  74,
  76,
  78,
  80,
  82,
  84,
  86,
  88,
  90,
  92,
  94,
  96,
  98,
  100,
  102,
  104,
  106,
  108,
  110,
  112,
  114,
  116,
  118,
  120,
  122,
  124,
  126,
  128,
  130,
  132,
  134,
  136,
  138,
  140,
  142,
  144,
  146,
  148,
  150,
  152,
  154,
  156,
  158,
  160,
  162,
  164,
  166,
  168,
  170,
  172,
  174,
  176,
  178,
  180,
  182,
  184,
  186,
  188,
  190,
  192,
  194,
  196,
  198,
  200,
  202,
  204,
  206,
  208,
  210,
  212,
  214,
  216,
  218,
  220,
  222,
  224,
  226,
  228,
  230,
  232,
  234,
  236,
  238,
  240,
  242,
  244,
  246,
  248,
  250,
  252,
  254,
  256,
  258,
  260,
  262,
  264,
  266,
  268,
  270,
  272,
  274,
  276,
  278,
  280,
  282,
  284,
  286,
  288,
  290,
  292,
  294,
  296,
  298,
  300,
  3

### Solución Valeria

In [1]:
##EJERCICIO 1
import numpy as np
def cong_method(d0:"Semilla1",d1:"Semilla2", N:"Número de elementos"):
    '''La función tiene el método congruencial para la sucesión D_n = ((n-1)D_{n−1} + (n-1)D_{n−2})
     para N>=3'''
    
    x = np.zeros(N)
    x[0] = d0
    x[1] = d1
    def vector(i):
        nonlocal x  
        x[i+2] = (N-1) * x[i+1] + (N-1) * x[i] 
    [vector(i) for i in range(N-2)]
    return x 

y = cong_method(0, 1, 3)
y

array([0., 1., 2.])

In [2]:
##EJERCICIO 2
variable = "relaciónn  requiere,  para obtener  el  valor  de un  cierto  término,  el conocimiento de los dos anteriores."
len([sp for sp in variable if sp == " "])

23

In [3]:
##EJERCICIO 3
frase = "Los números aleatorios son la base esencial."
[voc for voc in frase if voc not in "AÁaáEÉeéIÍiíOÓoóUÚuú"]

['L',
 's',
 ' ',
 'n',
 '́',
 'm',
 'r',
 's',
 ' ',
 'l',
 't',
 'r',
 's',
 ' ',
 's',
 'n',
 ' ',
 'l',
 ' ',
 'b',
 's',
 ' ',
 's',
 'n',
 'c',
 'l',
 '.']

In [4]:
##EJERCICIO 4
fr= frase.split()
[max for max in fr if len(max) < 4]

['Los', 'son', 'la']

In [5]:
##EJERCICIO 5
diccionario = frase.split()
list(map(len, diccionario))

[3, 8, 10, 3, 2, 4, 9]

In [6]:
##EJERCICIO 6
n = [i for i in range(1,1001) if [w for w in range(2,10) if i%w ==0]]
n

[2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 12,
 14,
 15,
 16,
 18,
 20,
 21,
 22,
 24,
 25,
 26,
 27,
 28,
 30,
 32,
 33,
 34,
 35,
 36,
 38,
 39,
 40,
 42,
 44,
 45,
 46,
 48,
 49,
 50,
 51,
 52,
 54,
 55,
 56,
 57,
 58,
 60,
 62,
 63,
 64,
 65,
 66,
 68,
 69,
 70,
 72,
 74,
 75,
 76,
 77,
 78,
 80,
 81,
 82,
 84,
 85,
 86,
 87,
 88,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 98,
 99,
 100,
 102,
 104,
 105,
 106,
 108,
 110,
 111,
 112,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 122,
 123,
 124,
 125,
 126,
 128,
 129,
 130,
 132,
 133,
 134,
 135,
 136,
 138,
 140,
 141,
 142,
 144,
 145,
 146,
 147,
 148,
 150,
 152,
 153,
 154,
 155,
 156,
 158,
 159,
 160,
 161,
 162,
 164,
 165,
 166,
 168,
 170,
 171,
 172,
 174,
 175,
 176,
 177,
 178,
 180,
 182,
 183,
 184,
 185,
 186,
 188,
 189,
 190,
 192,
 194,
 195,
 196,
 198,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 210,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 222,
 224,
 225,
 226,
 228,
 230,
 231,
 232,
 234,
 235,

## Solución estudiante 3 - Andrés Ramírez Villanueva

In [2]:
import numpy as np

In [71]:
## Ejercicio 1
def funcion(d1, d2, n):
    D=[d1,d2]
    for i in range(2,n):
        D.append((i)*(D[-1])+(i)*(D[-2]))
    return np.array(D)

funcion(0,1,8)

array([    0,     1,     2,     9,    44,   265,  1854, 14833])

In [72]:
## Ejercicio 2
cadena =  "relaciónn  requiere,  para obtener  el  valor  de un  cierto  término,  el conocimiento de los dos anteriores"
n = [x for x in cadena if x == " "]
n.count(" ") 

23

In [74]:
## Ejercicio 3
voc=['a','e','i','o','u','á','é','í','ó','ú']
vector = [x for x in cadena if x not in voc]
str(vector)

"['r', 'l', 'c', 'n', 'n', ' ', ' ', 'r', 'q', 'r', ',', ' ', ' ', 'p', 'r', ' ', 'b', 't', 'n', 'r', ' ', ' ', 'l', ' ', ' ', 'v', 'l', 'r', ' ', ' ', 'd', ' ', 'n', ' ', ' ', 'c', 'r', 't', ' ', ' ', 't', 'r', 'm', 'n', ',', ' ', ' ', 'l', ' ', 'c', 'n', 'c', 'm', 'n', 't', ' ', 'd', ' ', 'l', 's', ' ', 'd', 's', ' ', 'n', 't', 'r', 'r', 's']"

In [75]:
## Ejercicio 4 
var =  "relaciónn  requiere,  para obtener  el  valor  de un  cierto  término,  el conocimiento de los dos anteriores"
var = var.split()
eje4 = [x for x in variable if len(x) < 4]
eje4

['el', 'de', 'un', 'el', 'de', 'los', 'dos']

In [77]:
## Ejercicio 5
cadena = {x: len(x) for x in var}
cadena

{'relaciónn': 9,
 'requiere,': 9,
 'para': 4,
 'obtener': 7,
 'el': 2,
 'valor': 5,
 'de': 2,
 'un': 2,
 'cierto': 6,
 'término,': 8,
 'conocimiento': 12,
 'los': 3,
 'dos': 3,
 'anteriores': 10}

In [79]:
## Ejercicio 6
eje6 = [cont for cont in range (1, 1001) if True in [True for div in range (2, 10) if cont % div  == 0]]
eje6

[2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 12,
 14,
 15,
 16,
 18,
 20,
 21,
 22,
 24,
 25,
 26,
 27,
 28,
 30,
 32,
 33,
 34,
 35,
 36,
 38,
 39,
 40,
 42,
 44,
 45,
 46,
 48,
 49,
 50,
 51,
 52,
 54,
 55,
 56,
 57,
 58,
 60,
 62,
 63,
 64,
 65,
 66,
 68,
 69,
 70,
 72,
 74,
 75,
 76,
 77,
 78,
 80,
 81,
 82,
 84,
 85,
 86,
 87,
 88,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 98,
 99,
 100,
 102,
 104,
 105,
 106,
 108,
 110,
 111,
 112,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 122,
 123,
 124,
 125,
 126,
 128,
 129,
 130,
 132,
 133,
 134,
 135,
 136,
 138,
 140,
 141,
 142,
 144,
 145,
 146,
 147,
 148,
 150,
 152,
 153,
 154,
 155,
 156,
 158,
 159,
 160,
 161,
 162,
 164,
 165,
 166,
 168,
 170,
 171,
 172,
 174,
 175,
 176,
 177,
 178,
 180,
 182,
 183,
 184,
 185,
 186,
 188,
 189,
 190,
 192,
 194,
 195,
 196,
 198,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 210,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 222,
 224,
 225,
 226,
 228,
 230,
 231,
 232,
 234,
 235,